### ISSUE TITLE
Isolate hop project from application

### ISSUE THREAD

**Issue by pauloricardoferreira** [damavis/airflow-hop-plugin#26]
Hello.

Sorry for the English, I used google translator.

I would like to suggest a change to the xml.py file.

According to the documentation, it would be necessary to leave the hop artifacts in the home_home/project folder for the plugin to work correctly.

Analyzing the code I thought and tested the following solution.

the commented line is the original of the project and the line below is the change suggestion

#self.project_folder = f'{hop_home}/{project["projectHome"]}'

if hop_home == self.project_home:
    self.project_folder = self.project_home
else:
    self.project_folder = f'{hop_home}/{self.project_home}'

This way I can leave the hop project isolated from the hop application, gaining mobility.

for the documentation you could leave it like this:
If your project is in a custom location, in the apache airflow connection configuration, home_home must be the same as the folder where your project is, so the plugin works correctly.

Attention: it is necessary that the hop artifacts are in the Airflow container, in the same path.

![code](https://user-images.githubusercontent.com/70301866/204093083-63eca193-15a0-4071-a1cb-ae5a76aa89c3.PNG)

![hop](https://user-images.githubusercontent.com/70301866/204093421-db06c53c-d204-47bd-9af0-f46d4c1f5ada.PNG)

**Comment by pauloricardoferreira** [comment]
Error:

![image](https://user-images.githubusercontent.com/70301866/204095985-4a3126b6-cb7f-447a-af25-ba45a79bbec4.png)

**Comment by pauloricardoferreira** [comment]
Hello...

because the flow runs normally, but the airflow returns an error.


*** Reading local file: /opt/airflow/logs/dag_id=dag-w-teste/run_id=manual__2022-11-28T10:53:11.964359+00:00/task_id=tsk-w-teste/attempt=1.log
[2022-11-28, 10:53:12 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag-w-teste.tsk-w-teste manual__2022-11-28T10:53:11.964359+00:00 [queued]>
[2022-11-28, 10:53:12 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag-w-teste.tsk-w-teste manual__2022-11-28T10:53:11.964359+00:00 [queued]>
[2022-11-28, 10:53:12 UTC] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-28, 10:53:12 UTC] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-28, 10:53:12 UTC] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-28, 10:53:12 UTC] {taskinstance.py:1383} INFO - Executing <Task(HopWorkflowOperator): tsk-w-teste> on 2022-11-28 10:53:11.964359+00:00
[2022-11-28, 10:53:12 UTC] {standard_task_runner.py:54} INFO - Started process 6627 to run task
[2022-11-28, 10:53:12 UTC] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag-w-teste', 'tsk-w-teste', 'manual__2022-11-28T10:53:11.964359+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag-w-teste.py', '--cfg-path', '/tmp/tmp7xghbt2k']
[2022-11-28, 10:53:12 UTC] {standard_task_runner.py:83} INFO - Job 3: Subtask tsk-w-teste
[2022-11-28, 10:53:12 UTC] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***_dags/dag-w-teste.py
[2022-11-28, 10:53:13 UTC] {task_command.py:384} INFO - Running <TaskInstance: dag-w-teste.tsk-w-teste manual__2022-11-28T10:53:11.964359+00:00 [running]> on host 58ad4d15dc5e
[2022-11-28, 10:53:13 UTC] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=paulo.ricardo@agroterenas.com.br
AIRFLOW_CTX_DAG_OWNER=Agroterenas
AIRFLOW_CTX_DAG_ID=dag-w-teste
AIRFLOW_CTX_TASK_ID=tsk-w-teste
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T10:53:11.964359+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-28T10:53:11.964359+00:00
[2022-11-28, 10:53:13 UTC] {base.py:71} INFO - Using connection ID 'hop_default' for task execution.
[2022-11-28, 10:53:13 UTC] {operators.py:83} INFO - TESTES/W_TESTE.hwf: Workflow 'W_TESTE' was added to the list with id eeb56df5-06a9-45d9-bd09-d4a1afbc4be3
[2022-11-28, 10:53:13 UTC] {operators.py:87} INFO - TESTES/W_TESTE.hwf: Started OK
[2022-11-28, 10:53:13 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow_dags/airflow_hop/operators.py", line 92, in execute
    work_status_rs = conn.workflow_status(self.workflow, work_id)
  File "/opt/airflow_dags/airflow_hop/hooks.py", line 190, in workflow_status
    raise AirflowException('{}: {}'.format('HTTP', error))
airflow.exceptions.AirflowException: HTTP: Error 500 java.lang.NullPointerException
[2022-11-28, 10:53:13 UTC] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=dag-w-teste, task_id=tsk-w-teste, execution_date=20221128T105311, start_date=20221128T105312, end_date=20221128T105313
[2022-11-28, 10:53:13 UTC] {standard_task_runner.py:102} ERROR - Failed to execute job 3 for task tsk-w-teste (HTTP: Error 500 java.lang.NullPointerException; 6627)
[2022-11-28, 10:53:13 UTC] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-28, 10:53:13 UTC] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check

**Comment by pauloricardoferreira** [comment]
Add PR #27
